name: Build and Test CLI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make build
      - run: make deb
      - uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh_*.deb

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kubsh-deb
          path: ./artifact

      - run: ls -la ./artifact

      - run: |
          docker run --rm \
            -v ${{ github.workspace }}/artifact:/mnt \
            tyvik/kubsh_test:master
