name: Build and Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake debhelper

      - name: Build project
        run: make build

      - name: Build deb package
        run: make deb

      - name: List files
        run: ls -la *.deb ../*.deb || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh_*.deb
          if-no-files-found: error
