name: Build and Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake debhelper

      - name: Build project
        run: make build

      - name: Run checks
        run: ./build/bin/kubsh --version || true

      - name: Build deb package
        run: make deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubsh-deb
          path: ../kubsh_*.deb
