name: Find Artifacts

on:
  workflow_dispatch: {}

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List all artifacts in repo
        uses: actions/github-script@v7
        with:
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            })
            console.log("Found artifacts:")
            for (const a of artifacts.data.artifacts) {
              console.log(`- ${a.name} (id=${a.id}, size=${a.size_in_bytes}B, expired=${a.expired})`)
            }
